project_id = "sdcmbfdtafkzpimwjpij"

[functions.ux-analysis]
verify_jwt = true

[functions.google-vision-metadata]
verify_jwt = false

[functions.inpainting-service]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.context-detection]
verify_jwt = true

[functions.natural-ai-analysis]
verify_jwt = false

[functions.ai-insight-interpreter]
verify_jwt = false

[functions.stability-analysis]
verify_jwt = true

[functions.stability-mockup-generator]
verify_jwt = true