project_id = "sdcmbfdtafkzpimwjpij"

[functions.ux-analysis]
verify_jwt = false

[functions.google-vision-analysis]
verify_jwt = false

[functions.claude-vision-analysis] 
verify_jwt = false

[functions.stability-ai-analysis]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false