project_id = "sdcmbfdtafkzpimwjpij"

[functions.ux-analysis]
verify_jwt = true

[functions.group-ux-analysis]
verify_jwt = true

[functions.google-vision-metadata]
verify_jwt = false

[functions.inpainting-service]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.context-detection]
verify_jwt = true

[functions.natural-ai-analysis]
verify_jwt = false

[functions.ai-insight-interpreter]
verify_jwt = false

[functions.stability-analysis]
verify_jwt = true

[functions.stability-mockup-generator]
verify_jwt = true

[functions.inngest-dispatch]
verify_jwt = true

[functions.analysis-progress]
verify_jwt = false

[functions.ux-context-detection]
verify_jwt = true

[functions.ux-vision-openai]
verify_jwt = true

[functions.ux-vision-google]
verify_jwt = true

[functions.ux-ai-analysis]
verify_jwt = true

[functions.ux-synthesis]
verify_jwt = true

[functions.ux-orchestrator]
verify_jwt = true

[functions.start-ux-analysis]
verify_jwt = true

[functions.start-group-ux-analysis]
verify_jwt = true

[functions.group-ux-orchestrator]
verify_jwt = true

[functions.group-vision-openai]
verify_jwt = true

[functions.group-vision-google]
verify_jwt = true

[functions.group-ai-analysis]
verify_jwt = true

[functions.group-synthesis]
verify_jwt = true

[functions.inngest-webhook]
verify_jwt = false
