project_id = "sdcmbfdtafkzpimwjpij"

[functions.ux-analysis]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.context-detection]
verify_jwt = true