project_id = "sdcmbfdtafkzpimwjpij"

[functions.openai-test]
verify_jwt = false

[functions.ux-analysis]
verify_jwt = true

[functions.google-vision-metadata]
verify_jwt = false

[functions.ai-analysis]
verify_jwt = true

[functions.inpainting-service]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false